# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2XXOrderAddress(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, address_line_1: str=None, address_line_2: str=None, address_type: str=None, city: str=None, country_id: str=None, customer_id: int=None, full_name: str=None, id: int=None, order_id: int=None, phone: str=None, region: str=None, zip: str=None):  # noqa: E501
        """InlineResponse2XXOrderAddress - a model defined in Swagger

        :param address_line_1: The address_line_1 of this InlineResponse2XXOrderAddress.  # noqa: E501
        :type address_line_1: str
        :param address_line_2: The address_line_2 of this InlineResponse2XXOrderAddress.  # noqa: E501
        :type address_line_2: str
        :param address_type: The address_type of this InlineResponse2XXOrderAddress.  # noqa: E501
        :type address_type: str
        :param city: The city of this InlineResponse2XXOrderAddress.  # noqa: E501
        :type city: str
        :param country_id: The country_id of this InlineResponse2XXOrderAddress.  # noqa: E501
        :type country_id: str
        :param customer_id: The customer_id of this InlineResponse2XXOrderAddress.  # noqa: E501
        :type customer_id: int
        :param full_name: The full_name of this InlineResponse2XXOrderAddress.  # noqa: E501
        :type full_name: str
        :param id: The id of this InlineResponse2XXOrderAddress.  # noqa: E501
        :type id: int
        :param order_id: The order_id of this InlineResponse2XXOrderAddress.  # noqa: E501
        :type order_id: int
        :param phone: The phone of this InlineResponse2XXOrderAddress.  # noqa: E501
        :type phone: str
        :param region: The region of this InlineResponse2XXOrderAddress.  # noqa: E501
        :type region: str
        :param zip: The zip of this InlineResponse2XXOrderAddress.  # noqa: E501
        :type zip: str
        """
        self.swagger_types = {
            'address_line_1': str,
            'address_line_2': str,
            'address_type': str,
            'city': str,
            'country_id': str,
            'customer_id': int,
            'full_name': str,
            'id': int,
            'order_id': int,
            'phone': str,
            'region': str,
            'zip': str
        }

        self.attribute_map = {
            'address_line_1': 'address_line_1',
            'address_line_2': 'address_line_2',
            'address_type': 'address_type',
            'city': 'city',
            'country_id': 'country_id',
            'customer_id': 'customer_id',
            'full_name': 'full_name',
            'id': 'id',
            'order_id': 'order_id',
            'phone': 'phone',
            'region': 'region',
            'zip': 'zip'
        }
        self._address_line_1 = address_line_1
        self._address_line_2 = address_line_2
        self._address_type = address_type
        self._city = city
        self._country_id = country_id
        self._customer_id = customer_id
        self._full_name = full_name
        self._id = id
        self._order_id = order_id
        self._phone = phone
        self._region = region
        self._zip = zip

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2XXOrderAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_2XX_orderAddress of this InlineResponse2XXOrderAddress.  # noqa: E501
        :rtype: InlineResponse2XXOrderAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address_line_1(self) -> str:
        """Gets the address_line_1 of this InlineResponse2XXOrderAddress.


        :return: The address_line_1 of this InlineResponse2XXOrderAddress.
        :rtype: str
        """
        return self._address_line_1

    @address_line_1.setter
    def address_line_1(self, address_line_1: str):
        """Sets the address_line_1 of this InlineResponse2XXOrderAddress.


        :param address_line_1: The address_line_1 of this InlineResponse2XXOrderAddress.
        :type address_line_1: str
        """
        if address_line_1 is None:
            raise ValueError("Invalid value for `address_line_1`, must not be `None`")  # noqa: E501

        self._address_line_1 = address_line_1

    @property
    def address_line_2(self) -> str:
        """Gets the address_line_2 of this InlineResponse2XXOrderAddress.


        :return: The address_line_2 of this InlineResponse2XXOrderAddress.
        :rtype: str
        """
        return self._address_line_2

    @address_line_2.setter
    def address_line_2(self, address_line_2: str):
        """Sets the address_line_2 of this InlineResponse2XXOrderAddress.


        :param address_line_2: The address_line_2 of this InlineResponse2XXOrderAddress.
        :type address_line_2: str
        """
        if address_line_2 is None:
            raise ValueError("Invalid value for `address_line_2`, must not be `None`")  # noqa: E501

        self._address_line_2 = address_line_2

    @property
    def address_type(self) -> str:
        """Gets the address_type of this InlineResponse2XXOrderAddress.


        :return: The address_type of this InlineResponse2XXOrderAddress.
        :rtype: str
        """
        return self._address_type

    @address_type.setter
    def address_type(self, address_type: str):
        """Sets the address_type of this InlineResponse2XXOrderAddress.


        :param address_type: The address_type of this InlineResponse2XXOrderAddress.
        :type address_type: str
        """
        if address_type is None:
            raise ValueError("Invalid value for `address_type`, must not be `None`")  # noqa: E501

        self._address_type = address_type

    @property
    def city(self) -> str:
        """Gets the city of this InlineResponse2XXOrderAddress.


        :return: The city of this InlineResponse2XXOrderAddress.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this InlineResponse2XXOrderAddress.


        :param city: The city of this InlineResponse2XXOrderAddress.
        :type city: str
        """
        if city is None:
            raise ValueError("Invalid value for `city`, must not be `None`")  # noqa: E501

        self._city = city

    @property
    def country_id(self) -> str:
        """Gets the country_id of this InlineResponse2XXOrderAddress.


        :return: The country_id of this InlineResponse2XXOrderAddress.
        :rtype: str
        """
        return self._country_id

    @country_id.setter
    def country_id(self, country_id: str):
        """Sets the country_id of this InlineResponse2XXOrderAddress.


        :param country_id: The country_id of this InlineResponse2XXOrderAddress.
        :type country_id: str
        """
        if country_id is None:
            raise ValueError("Invalid value for `country_id`, must not be `None`")  # noqa: E501

        self._country_id = country_id

    @property
    def customer_id(self) -> int:
        """Gets the customer_id of this InlineResponse2XXOrderAddress.


        :return: The customer_id of this InlineResponse2XXOrderAddress.
        :rtype: int
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: int):
        """Sets the customer_id of this InlineResponse2XXOrderAddress.


        :param customer_id: The customer_id of this InlineResponse2XXOrderAddress.
        :type customer_id: int
        """
        if customer_id is None:
            raise ValueError("Invalid value for `customer_id`, must not be `None`")  # noqa: E501

        self._customer_id = customer_id

    @property
    def full_name(self) -> str:
        """Gets the full_name of this InlineResponse2XXOrderAddress.


        :return: The full_name of this InlineResponse2XXOrderAddress.
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name: str):
        """Sets the full_name of this InlineResponse2XXOrderAddress.


        :param full_name: The full_name of this InlineResponse2XXOrderAddress.
        :type full_name: str
        """
        if full_name is None:
            raise ValueError("Invalid value for `full_name`, must not be `None`")  # noqa: E501

        self._full_name = full_name

    @property
    def id(self) -> int:
        """Gets the id of this InlineResponse2XXOrderAddress.


        :return: The id of this InlineResponse2XXOrderAddress.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this InlineResponse2XXOrderAddress.


        :param id: The id of this InlineResponse2XXOrderAddress.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def order_id(self) -> int:
        """Gets the order_id of this InlineResponse2XXOrderAddress.


        :return: The order_id of this InlineResponse2XXOrderAddress.
        :rtype: int
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: int):
        """Sets the order_id of this InlineResponse2XXOrderAddress.


        :param order_id: The order_id of this InlineResponse2XXOrderAddress.
        :type order_id: int
        """

        self._order_id = order_id

    @property
    def phone(self) -> str:
        """Gets the phone of this InlineResponse2XXOrderAddress.


        :return: The phone of this InlineResponse2XXOrderAddress.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this InlineResponse2XXOrderAddress.


        :param phone: The phone of this InlineResponse2XXOrderAddress.
        :type phone: str
        """
        if phone is None:
            raise ValueError("Invalid value for `phone`, must not be `None`")  # noqa: E501

        self._phone = phone

    @property
    def region(self) -> str:
        """Gets the region of this InlineResponse2XXOrderAddress.


        :return: The region of this InlineResponse2XXOrderAddress.
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region: str):
        """Sets the region of this InlineResponse2XXOrderAddress.


        :param region: The region of this InlineResponse2XXOrderAddress.
        :type region: str
        """
        if region is None:
            raise ValueError("Invalid value for `region`, must not be `None`")  # noqa: E501

        self._region = region

    @property
    def zip(self) -> str:
        """Gets the zip of this InlineResponse2XXOrderAddress.


        :return: The zip of this InlineResponse2XXOrderAddress.
        :rtype: str
        """
        return self._zip

    @zip.setter
    def zip(self, zip: str):
        """Sets the zip of this InlineResponse2XXOrderAddress.


        :param zip: The zip of this InlineResponse2XXOrderAddress.
        :type zip: str
        """
        if zip is None:
            raise ValueError("Invalid value for `zip`, must not be `None`")  # noqa: E501

        self._zip = zip
